#+TITLE: PNe in SPLUS
#+EMAIL: gsoto.angel@gmail.com
* Looking for Planetary nebulae in SPLUS

** Testing of Gustavo program

I implemented the script of Gustavo on Jupyter:

: ipython/Testing program of Gustavo to get SPLUS data using criterio.ipynb

For the search of PNe.

#+begin_example criterio  

'R_PStotal <= 20, e_R_PStotal <= 0.2', 'e_F660_PStotal <= 0.2', 'e_I_PStotal <= 0.2', 
'(R_PStotal - F660_PStotal) >= 0.43*(R_PStotal - I_PStotal) + 0.65', 'R_PStotal - F660_PStotal <= -6.8*(R_PStotal - I_PStotal) - 1.3', 
'(F515_PStotal - F660_PStotal) >= 0.22', '(F515_PStotal - F660_PStotal) >= 2.7*(F515_PStotal - F861_PStotal) + 2.15', '(G_PStotal - F515_PStotal) <= 0.12*(F660_PStotal - R_PStotal) - 0.01', 
'(G_PStotal - F515_PStotal) <= -1.1*(F660_PStotal - R_PStotal) - 1.07', '(Z_PStotal - F660_PStotal) >= 0.2319*(Z_PStotal - G_PStotal) + 0.85', 
'(Z_PStotal - F660_PStotal) >= -1.3*(Z_PStotal - G_PStotal) + 1.7', '(F410_PStotal - F660_PStotal) >= 8.0*(G_PStotal - I_PStotal) + 4.5', 
'(F410_PStotal - F660_PStotal) >= 0.8*(G_PStotal - I_PStotal) + 0.55'

#+end_example

#+begin_example criterio  

'R_aper_6 <= 20, e_R_aper_6 <= 0.2', 'e_F660_aper_6 <= 0.2', 'e_I_aper_6 <= 0.2', 
'(R_aper_6 - F660_aper_6) >= 0.43*(R_aper_6 - I_aper_6) + 0.65', 'R_aper_6 - F660_aper_6 <= -6.8*(R_aper_6 - I_aper_6) - 1.3', 
'(F515_aper_6 - F660_aper_6) >= 0.22', '(F515_aper_6 - F660_aper_6) >= 2.7*(F515_aper_6 - F861_aper_6) + 2.15', '(G_aper_6 - F515_aper_6) <= 0.12*(F660_aper_6 - R_aper_6) - 0.01', 
'(G_aper_6 - F515_aper_6) <= -1.1*(F660_aper_6 - R_aper_6) - 1.07', '(Z_aper_6 - F660_aper_6) >= 0.2319*(Z_aper_6 - G_aper_6) + 0.85', 
'(Z_aper_6 - F660_aper_6) >= -1.3*(Z_aper_6 - G_aper_6) + 1.7', '(F410_aper_6 - F660_aper_6) >= 8.0*(G_aper_6 - I_aper_6) + 4.5', 
'(F410_aper_6 - F660_aper_6) >= 0.8*(G_aper_6 - I_aper_6) + 0.55'

#+end_example

** Applying the color criterion got with the filter Viironen.
 
I applied the Viironen color criterion to all MAIN catalogs using the Gustavo code. 

#+begin_example Viironen  

'R_PStotal <= 20.5', e_R_PStotal <= 0.2', 'e_F660_PStotal <= 0.2', 'e_I_PStotal <= 0.2', 
'(R_PStotal - F660_PStotal) >= 0.15*(R_PStotal - I_PStotal) + 0.53'

#+end_example

: Splus-queries.ipynb

Result:
: halphaemitter-allmain.fits 

+ I removed all the objects that have 99 value in any filter.

: SPLUS_DR2_dataRelease_2020_HaphaVii.py

Result:
: halphaemitter-allmain-99.tab

 - I applied PCA and logistic regression algorithms to the results.
   : pca-splus_idr2-3class-SMOTE_predict.py 

   For that I used my laptop.
   
#+begin_example 
PN-pc-halphaemitter-allmain-99.tab
SySt-pc-halphaemitter-allmain-99.tab
#+end_example 
   
   Two galactic known PNe were select. One extragalactic (in a globular cluster) PN also was selected.

  - I made the colour diagrams:
    : color-diagrams-splusdr2_automatic-v2.py
  - And the photo-spectra:
    : photo-spectra-SPLUSDR2-v2.py  

*** Next step
+ Continue the analysis.
+ Make the same for a aperture of 6 arcsec.
